# Generated by Django 3.1.6 on 2021-03-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user', '0005_auto_20210224_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locationId',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
