# Generated by Django 3.1.6 on 2021-03-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=16)),
                ('description', models.TextField(default='')),
                ('image', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('categoryId', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
                ('ownerId', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
