# Generated by Django 3.1.6 on 2021-03-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210325_1325'),
        ('product', '0002_userfavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(blank='True', default='Annet', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.category', to_field='title'),
        ),
    ]
