# Generated by Django 3.1.6 on 2021-02-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iamge',
            field=models.CharField(default='', max_length=255),
        ),
    ]
