# Generated by Django 3.1.6 on 2021-03-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210325_1325'),
        ('product', '0003_auto_20210325_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(blank='True', default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.category'),
        ),
    ]
