# Generated by Django 3.1.6 on 2021-02-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
