# Generated by Django 3.1.6 on 2021-02-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210223_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='email',
            new_name='ownerId',
        ),
    ]
