# Generated by Django 3.1.6 on 2021-03-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
