# Generated by Django 3.1.7 on 2021-03-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210316_1544'),
        ('product', '0014_remove_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='locationId',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
