# Generated by Django 3.1.7 on 2021-03-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_locationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='locationId',
        ),
    ]
